---

services:
  redis:
    image: redis:latest
    restart: always
    container_name: fc-redis
    expose:
      - "6379"
    volumes:
      - ./data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=""
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  mysql:
      image: mysql:latest
      container_name: fc-mysql
      expose:
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_NAME
      volumes:
        - ./data/mysql1:/var/lib/mysql
      restart: always
  app:
    image: flesh-cards:local
    container_name: fc-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
      - redis
    