---

services:
  redis:
    image: redis:latest
    restart: always
    container_name: fc-redis
    expose:
      - "6379"
    volumes:
      - ./data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=""
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  mysql:
      image: mysql:latest
      container_name: fc-mysql
      expose:
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_NAME
      volumes:
        - ./data/mysql1:/var/lib/mysql
      restart: always
  debug:
    build:
      dockerfile: D:/User/smth/go/goProjects/flesh-cards-backup/DockerfileDebug
      # context: ../../
    ports:
      - 2345:2345
    command: ["/go/bin/dlv", "--listen=:2345", "--headless=true", "--log=true", "--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc", "--accept-multiclient", "--api-version=2", "exec", "./app"]
    # command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./usr/local/src/app"
    depends_on:
      - redis
      - mysql